[build]
command = "next build"
base = "."
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@netlify-labs/plugin-next-edge"

[[plugins]]
package = "@netlify-labs/plugin-edge-handlers-test"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200

[functions]
included_files = [
  "!node_modules/sharp/vendor/8.12.2/darwin-*/**/*",
  "!node_modules/sharp/build/Release/sharp-darwin-*"
]
